package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class LoginpController {
	@FXML
	private AnchorPane logroot;
	@FXML
	private TextField user;
	@FXML
	private TextField mdp;
	@FXML
	private Button valider;

	// Event Listener on Button[#valider].onAction
	@FXML
	public void validation(ActionEvent event) {
		// TODO Autogenerated
	}
}
